### ISSUE TITLE
June 8th demo

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#474]
# rationale
Distributed web conf. Show that underlying dat tools work in the browser. The data, paper, and the metadata (index.html, etc) for a dataset can be packaged together into a single movable, archivable, research artifact.

Brewster wrote about these 'movable' data+web bundles here: http://blog.archive.org/2016/04/05/getting-back-to-view-source-on-the-web-the-movable-web-decentralized-web/

# demo
- folder has index.html
- drag and drop folder to a browser
- app renders website (static)
- app gives you a link
- put link into another browser
- see that same website rendered properly

# todo
- [x] hyperdrive works in browser
- [x] webrtc-swarm + hyperdrive on web page
- [ ] module to render website from a hyperdrive in the browser
